### ISSUE TITLE
the script only says this is duplicate window closing.. it doesnt close the tab as shown in demo here is my code

### ISSUE THREAD

**Issue by keaikitse** [nitinjs/jquery-duplicatewindow#1]
<?php
session_start();
if($_SESSION['login'])
{
?>

<style type="text/css"> 
	html {

	
	background:url(css/bg.jpg) no-repeat center fixed;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size:cover;
	background-size: cover;
}
.logo{
	text-indent: 999999px;
	background: ('css/logo.png');
	width:370px;
	height:150px;
}

	</style>

<!DOCTYPE html>
<html >
<head>
	<script type="text/javascript" >
   function preventBack(){window.history.forward();}
    setTimeout("preventBack()", 0);
    window.onunload=function(){null};
</script>

<meta charset="UTF-8">
<script src="https://code.jquery.com/jquery-1.12.4.min.js" type="text/javascript"></script>
    <script src="Duplicate.js"></script>
<title>welcome</title>
</head>
<body bg color="#E6E6FA">
	<script type="text/javascript">
        $(document).ready(function () {
            if (window.IsDuplicate()) {
                alert("this is duplicate window\n\n closing...");
                window.close();
            }
        });
    </script>  

<p>Welcome : <?php echo $_SESSION['login'];?> | <a href="logout.php">Logout</a> </p>
<p><a href="kk.php">Go to Cape Union Mart Group</a></p>
<p><a href="userlog.php">User Access log</a></p>
 </body>
</html>
<?php
} else{
header('location:logout.php');
}
?>

**Comment by nitinjs** [comment]
the script only says this is duplicate that means **its working**

double check whatever you have wrote inside the if condition
